name: my_taraji
description: "My Taraji futball club"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.0.9
  enefty_icons: ^1.0.7
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  motion_tab_bar_v2: ^0.3.0
  flutter_tabler_icons: ^1.11.0
  fluentui_system_icons: ^1.1.222
  simple_animation_progress_bar: ^1.6.0
  curved_navigation_bar: ^1.0.3
  flare_flutter: ^3.0.2
  liquid_swipe: ^3.1.0
  flutter_custom_clippers: ^2.1.0
  page_transition: ^2.1.0
  flutter_xlider: ^3.5.0
  http: ^1.1.2
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.1
  geolocator: ^10.1.0
  mask_text_input_formatter: ^2.7.0
  intl: ^0.19.0
  device_info: ^2.0.3
  provider: ^6.1.1
  webview_flutter: ^2.0.9
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/pngs/
    - images/pngs/campaigns/
    - images/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
